### ISSUE TITLE
class powers sometimes don't update correctly (warlock)

### ISSUE THREAD

**Issue by Whysz** [kesava-wow/kuinameplates2#118] opened 2016-09-30 11:33 UTC
The resources at the personal nameplate sometimes won't update correctly. Usualy this happens if one or more soul shards are refunded by soul conduit after casting a spell. After casting another soul shard consuming spell everything is as it should be, if no soul shard is refunded in that cast.

![wowscrnshot_093016_130136](https://cloud.githubusercontent.com/assets/22542551/18990427/0aab1c8e-8712-11e6-876c-b855c825009a.jpg)

Edit: As seen in the screenshot, the unitframes show 1 soul shard but the personal nameplate shows 0.

**Comment by niichtsShaiaz** [comment] 2016-09-30 13:37
How did you even get it to show the personal resource ? I can't get it working on my monk / rogue.

**Comment by kesava-wow** [comment] 2016-09-30 16:22
@niichtsShaiaz: /knp > class powers.

**Comment by kesava-wow** [comment] 2017-02-20 08:23
can't reproduce this, guessing it was fixed in 7.1.5. Let me know if it still happens.

**Closed by kesava-wow** 2017-02-20 08:23 UTC
Labels: bug, unconfirmed

**Comment by kesava-wow** [comment] 2017-06-22 17:28
https://github.com/kesava-wow/kuinameplates2/issues/209
